# Generated by Django 5.2.4 on 2025-07-07 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Docentes',
            new_name='Profesores',
        ),
    ]
